

# Ce bloc dit à Symfony : "Quand on tape /api/doc, lance le contrôleur de Nelmio"
app.swagger_ui:
    path: /api/doc
    methods: [GET]
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# Ce bloc permet à l'interface de lire les données JSON
app.swagger_json:
    path: /api/doc.json
    methods: [GET]
    defaults: { _controller: nelmio_api_doc.controller.swagger }