services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_db
    volumes:
      - db-data:/var/lib/mysql

  php:
    build: docker/php
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - db

  nginx:
    image: nginx:1.28
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/backend
      - ./frontend:/var/www/frontend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # Ce service ne sert qu'à compiler le Sass
  sass:
    image: node:25
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
    # Commande pour installer Sass et compiler en boucle (watch)
    command: >
      sh -c "npm install -g sass && 
            sass --watch scss/style.scss:css/style.css --poll"

  phpmyadmin:
    image: phpmyadmin:5.2 
    container_name: phpmyadmin_container
    ports:
      - "8081:80" # On utilise le port 8081 (car 8080 est déjà pris par ton site)
    environment:
      - PMA_HOST=db # On dit à PhpMyAdmin de se connecter au service "db"
      - PMA_ARBITRARY=1 # Permet de changer d'hôte si besoin
    depends_on:
      - db

volumes:
  db-data: