nelmio_api_doc :
    documentation :
        info:
            title: Restaurant API
            description: Documentation de l'API Restaurant Studi.
            version : 1.0.0
        components :
            securitySchemes :
                X-AUTH-TOKEN:
                    type : apiKey
                    in: header
                    name: X-AUTH-TOKEN
                    
        security:
            - X-AUTH-TOKEN: []
    areas:
        path_patterns:
            - ^/api(?!/doc$) 
            